name: Deploy Flutter Web App to Vercel

on:
  push:
    branches: [ main ]  # Or your default branch
  workflow_dispatch:    # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29'  # Set to user requested version
          channel: 'stable' # Uncommented as 3.29 is listed as stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter web
        env: # Make secrets available as environment variables for the run command
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        # ADDED: --dart-define flags
        run: flutter build web --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: List build directory contents (for debugging)
        run: ls -la build/web

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./build/web
        run: vercel deploy --prebuilt --prod --confirm --token $VERCEL_TOKEN


