name: Deploy Flutter Web App

on:
  push:
    branches: [ main ]  # Or your default branch
  workflow_dispatch:    # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'  # Specify your Flutter version
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get
      
      - name: Set up environment variables
        run: |
          # Create the environment.js file that will override the default ENV in index.html
          echo "window.ENV = {};" > web/environment.js
          echo "window.ENV.SUPABASE_URL = '${{ vars.SUPABASE_URL }}';" >> web/environment.js
          echo "window.ENV.SUPABASE_ANON_KEY = '${{ secrets.SUPABASE_ANON_KEY }}';" >> web/environment.js
      
      - name: Build Flutter web
        run: flutter build web --release

      # Example deployment step (using GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          
      # Alternatively, you could deploy to other platforms
      # - name: Deploy to Firebase
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      #     channelId: live


